name: Run rspec, rubocop-rails

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: docker-compose build
        run: docker-compose build

      - name: docker-compose up -d
        run: docker-compose up -d

      - name: setup db
        run: docker-compose run --rm backend rails db:create db:migrate

      - name: rspec
        run: docker-compose run --rm backend rspec

      - name: rubocop
        run: docker-compose run --rm backend rubocop

      - name: docker-compose down
        run: docker-compose down

